from .dr_science import *
from .elon import *
from .elon2 import *
from .cpp_coding import *
from .react_template import *
from .rewoo_template import *
from .openai_template import *
from .vanilla_template import *
from .openai_memory_template import *
from .vanilla-ziyu import *
from .scholar-ziyu import *
from .vanilla_agent import *
from .scholar_agent import *
from .health_agent import *
from .recipe_agent import *
